### ISSUE TITLE
QE wannier_ham.x bug (Solved)

### ISSUE THREAD

**Issue by zanatkamel** [dkorotin/exchanges#1]
Dear D. Korotin
In order to calculate exchange coupling parameters with exchange code using QE and their PP interfaces (wannier_ham.x)  (I try both versions 5.4 and 6.0)  I found a bug (or just an error from me!) but i don't know where to address it here or at qe forum.  So I prefer to discuss it here, because it concern directly your exchange code.

About the Bug, 
i get this system.am file:

>
> &codestamp
> QE_6.0   
> 
> &cell
>  0.999999606
>   4.70721  2.71771  0.00000
>   4.70721 -8.15313  0.00000
>   0.00000  0.00000 20.65849
>  
> &atoms
>    16
>  Fe1   0.00000  0.00000  0.00000
>  Fe1   0.00000  0.00000 10.32924
>  Fe2   4.70721 -2.71771  0.00000
>  Fe2   4.70721 -2.71771 10.32924
>  W     0.00000  0.00000  5.16462
>  W     4.70721 -2.71771 -5.16462
>  W     4.70721 -2.71771  5.16462
>  W     0.00000  0.00000 -5.16462
>  N     1.56907  2.71771  7.76139
>  N    -1.56907  2.71771 -7.76139
>  N     1.56907  2.71771  2.56785
>  N     1.56907 -2.71771  2.56785
>  N     1.56907 -2.71771  7.76139
>  N    -1.56907  2.71771 -2.56785
>  N     3.13814 -0.00000 -7.76139
>  N     3.13814 -0.00000 -2.56785
>  
> &nelec
>   77.22
>  
> &efermi
>  18.9259
>  
> !# Basis description:
> !# dim, nblocks
> !# atom_sym, atom_num, l_sym, block_dim, block_start, orbitals(1:block_dim)
> &basis
> 64  15
> Fe1  1 d 5   1     7 8 6 9 5
> Fe1  2 d 5   6     7 8 6 9 5
> Fe2  3 d 5  11     7 8 6 9 5
> Fe2  4 d 5  16     7 8 6 9 5
> W    5 d 5  21     7 8 6 9 5
> W    6 d 5  26     7 8 6 9 5
> W    7 d 5  31     7 8 6 9 5
> W    8 d 5  36     7 8 6 9 5
> N    9 p 3  41     3 4 2
> N   10 p 3  44     3 4 2
> N   11 p 3  47     3 4 2
> N   12 p 1  50     3
> **Fe1  1 d 5  51     7 8 6 9 5**
> **Fe1  2 d 5  56     7 8 6 9 5**
> **Fe2  3 d 4  61     7 8 6 9**
> 

as you can note that the 8-N atoms not fully treated, in basis tag, and replaced with the first atoms, see atoms tag.  
There is no problem with nspin=1 (non-polarized calculation). With nspin =2 the problem appeared in the spin # 1 and the second spin is OK. I cut/past the header file of wannier_ham.x output to clarify this point.  The problem appeared at nwan = 51 for spin 1.

>   Check: negative/imaginary core charge=   -0.000044    0.000000
     negative rho (up, down):  1.377E-01 1.377E-01
     Spin 1
       Wannier #  1 centered on atom Fe1 (position  0.00000 0.00000 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier #  2 centered on atom Fe1 (position  0.00000 0.00000 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier #  3 centered on atom Fe1 (position  0.00000 0.00000 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier #  4 centered on atom Fe1 (position  0.00000 0.00000 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
       Wannier #  5 centered on atom Fe1 (position  0.00000 0.00000 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=5
       Wannier #  6 centered on atom Fe1 (position  0.00000 0.0000010.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier #  7 centered on atom Fe1 (position  0.00000 0.0000010.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier #  8 centered on atom Fe1 (position  0.00000 0.0000010.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier #  9 centered on atom Fe1 (position  0.00000 0.0000010.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
       Wannier # 10 centered on atom Fe1 (position  0.00000 0.0000010.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=5
       Wannier # 11 centered on atom Fe2 (position  4.70721-2.71771 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier # 12 centered on atom Fe2 (position  4.70721-2.71771 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier # 13 centered on atom Fe2 (position  4.70721-2.71771 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier # 14 centered on atom Fe2 (position  4.70721-2.71771 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
       Wannier # 15 centered on atom Fe2 (position  4.70721-2.71771 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=5
       Wannier # 16 centered on atom Fe2 (position  4.70721-2.7177110.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier # 17 centered on atom Fe2 (position  4.70721-2.7177110.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier # 18 centered on atom Fe2 (position  4.70721-2.7177110.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier # 19 centered on atom Fe2 (position  4.70721-2.7177110.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
       Wannier # 20 centered on atom Fe2 (position  4.70721-2.7177110.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=5
       Wannier # 21 centered on atom W   (position  0.00000 0.00000 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier # 22 centered on atom W   (position  0.00000 0.00000 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier # 23 centered on atom W   (position  0.00000 0.00000 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier # 24 centered on atom W   (position  0.00000 0.00000 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
       Wannier # 25 centered on atom W   (position  0.00000 0.00000 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=5
       Wannier # 26 centered on atom W   (position  4.70721-2.71771-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier # 27 centered on atom W   (position  4.70721-2.71771-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier # 28 centered on atom W   (position  4.70721-2.71771-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier # 29 centered on atom W   (position  4.70721-2.71771-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
       Wannier # 30 centered on atom W   (position  4.70721-2.71771-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=5
       Wannier # 31 centered on atom W   (position  4.70721-2.71771 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier # 32 centered on atom W   (position  4.70721-2.71771 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier # 33 centered on atom W   (position  4.70721-2.71771 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier # 34 centered on atom W   (position  4.70721-2.71771 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
       Wannier # 35 centered on atom W   (position  4.70721-2.71771 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=5
       Wannier # 36 centered on atom W   (position  0.00000 0.00000-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier # 37 centered on atom W   (position  0.00000 0.00000-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier # 38 centered on atom W   (position  0.00000 0.00000-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier # 39 centered on atom W   (position  0.00000 0.00000-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
       Wannier # 40 centered on atom W   (position  0.00000 0.00000-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=5
       Wannier # 41 centered on atom N   (position  1.56907 2.71771 7.76139 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=1
       Wannier # 42 centered on atom N   (position  1.56907 2.71771 7.76139 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=2
       Wannier # 43 centered on atom N   (position  1.56907 2.71771 7.76139 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=3
       Wannier # 44 centered on atom N   (position -1.56907 2.71771-7.76139 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=1
       Wannier # 45 centered on atom N   (position -1.56907 2.71771-7.76139 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=2
       Wannier # 46 centered on atom N   (position -1.56907 2.71771-7.76139 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=3
       Wannier # 47 centered on atom N   (position  1.56907 2.71771 2.56785 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=1
       Wannier # 48 centered on atom N   (position  1.56907 2.71771 2.56785 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=2
       Wannier # 49 centered on atom N   (position  1.56907 2.71771 2.56785 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=3
       Wannier # 50 centered on atom N   (position  1.56907-2.71771 2.56785 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=1
       Wannier # 51 centered on atom Fe1 (position  0.00000 0.00000 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier # 52 centered on atom Fe1 (position  0.00000 0.00000 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier # 53 centered on atom Fe1 (position  0.00000 0.00000 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier # 54 centered on atom Fe1 (position  0.00000 0.00000 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
       Wannier # 55 centered on atom Fe1 (position  0.00000 0.00000 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=5
       Wannier # 56 centered on atom Fe1 (position  0.00000 0.0000010.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier # 57 centered on atom Fe1 (position  0.00000 0.0000010.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier # 58 centered on atom Fe1 (position  0.00000 0.0000010.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier # 59 centered on atom Fe1 (position  0.00000 0.0000010.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
       Wannier # 60 centered on atom Fe1 (position  0.00000 0.0000010.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=5
       Wannier # 61 centered on atom Fe2 (position  4.70721-2.71771 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier # 62 centered on atom Fe2 (position  4.70721-2.71771 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier # 63 centered on atom Fe2 (position  4.70721-2.71771 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier # 64 centered on atom Fe2 (position  4.70721-2.71771 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
     Spin 2
       Wannier #  1 centered on atom Fe1 (position  0.00000 0.00000 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier #  2 centered on atom Fe1 (position  0.00000 0.00000 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier #  3 centered on atom Fe1 (position  0.00000 0.00000 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier #  4 centered on atom Fe1 (position  0.00000 0.00000 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
       Wannier #  5 centered on atom Fe1 (position  0.00000 0.00000 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=5
       Wannier #  6 centered on atom Fe1 (position  0.00000 0.0000010.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier #  7 centered on atom Fe1 (position  0.00000 0.0000010.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier #  8 centered on atom Fe1 (position  0.00000 0.0000010.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier #  9 centered on atom Fe1 (position  0.00000 0.0000010.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
       Wannier # 10 centered on atom Fe1 (position  0.00000 0.0000010.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=5
       Wannier # 11 centered on atom Fe2 (position  4.70721-2.71771 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier # 12 centered on atom Fe2 (position  4.70721-2.71771 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier # 13 centered on atom Fe2 (position  4.70721-2.71771 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier # 14 centered on atom Fe2 (position  4.70721-2.71771 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
       Wannier # 15 centered on atom Fe2 (position  4.70721-2.71771 0.00000 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=5
       Wannier # 16 centered on atom Fe2 (position  4.70721-2.7177110.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier # 17 centered on atom Fe2 (position  4.70721-2.7177110.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier # 18 centered on atom Fe2 (position  4.70721-2.7177110.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier # 19 centered on atom Fe2 (position  4.70721-2.7177110.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
       Wannier # 20 centered on atom Fe2 (position  4.70721-2.7177110.32924 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=5
       Wannier # 21 centered on atom W   (position  0.00000 0.00000 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier # 22 centered on atom W   (position  0.00000 0.00000 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier # 23 centered on atom W   (position  0.00000 0.00000 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier # 24 centered on atom W   (position  0.00000 0.00000 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
       Wannier # 25 centered on atom W   (position  0.00000 0.00000 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=5
       Wannier # 26 centered on atom W   (position  4.70721-2.71771-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier # 27 centered on atom W   (position  4.70721-2.71771-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier # 28 centered on atom W   (position  4.70721-2.71771-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier # 29 centered on atom W   (position  4.70721-2.71771-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
       Wannier # 30 centered on atom W   (position  4.70721-2.71771-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=5
       Wannier # 31 centered on atom W   (position  4.70721-2.71771 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier # 32 centered on atom W   (position  4.70721-2.71771 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier # 33 centered on atom W   (position  4.70721-2.71771 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier # 34 centered on atom W   (position  4.70721-2.71771 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
       Wannier # 35 centered on atom W   (position  4.70721-2.71771 5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=5
       Wannier # 36 centered on atom W   (position  0.00000 0.00000-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=1
       Wannier # 37 centered on atom W   (position  0.00000 0.00000-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=2
       Wannier # 38 centered on atom W   (position  0.00000 0.00000-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=3
       Wannier # 39 centered on atom W   (position  0.00000 0.00000-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=4
       Wannier # 40 centered on atom W   (position  0.00000 0.00000-5.16462 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=2, m=5
       Wannier # 41 centered on atom N   (position  1.56907 2.71771 7.76139 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=1
       Wannier # 42 centered on atom N   (position  1.56907 2.71771 7.76139 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=2
       Wannier # 43 centered on atom N   (position  1.56907 2.71771 7.76139 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=3
       Wannier # 44 centered on atom N   (position -1.56907 2.71771-7.76139 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=1
       Wannier # 45 centered on atom N   (position -1.56907 2.71771-7.76139 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=2
       Wannier # 46 centered on atom N   (position -1.56907 2.71771-7.76139 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=3
       Wannier # 47 centered on atom N   (position  1.56907 2.71771 2.56785 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=1
       Wannier # 48 centered on atom N   (position  1.56907 2.71771 2.56785 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=2
       Wannier # 49 centered on atom N   (position  1.56907 2.71771 2.56785 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=3
       Wannier # 50 centered on atom N   (position  1.56907-2.71771 2.56785 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=1
       Wannier # 51 centered on atom N   (position  1.56907-2.71771 2.56785 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=2
       Wannier # 52 centered on atom N   (position  1.56907-2.71771 2.56785 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=3
       Wannier # 53 centered on atom N   (position  1.56907-2.71771 7.76139 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=1
       Wannier # 54 centered on atom N   (position  1.56907-2.71771 7.76139 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=2
       Wannier # 55 centered on atom N   (position  1.56907-2.71771 7.76139 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=3
       Wannier # 56 centered on atom N   (position -1.56907 2.71771-2.56785 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=1
       Wannier # 57 centered on atom N   (position -1.56907 2.71771-2.56785 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=2
       Wannier # 58 centered on atom N   (position -1.56907 2.71771-2.56785 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=3
       Wannier # 59 centered on atom N   (position  3.13814-0.00000-7.76139 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=1
       Wannier # 60 centered on atom N   (position  3.13814-0.00000-7.76139 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=2
       Wannier # 61 centered on atom N   (position  3.13814-0.00000-7.76139 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=3
       Wannier # 62 centered on atom N   (position  3.13814-0.00000-2.56785 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=1
       Wannier # 63 centered on atom N   (position  3.13814-0.00000-2.56785 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=2
       Wannier # 64 centered on atom N   (position  3.13814-0.00000-2.56785 )
         Bands for generation: from  41 to 115
         Trial wavefunction ingredients:
          1.0000000000 of l=1, m=3`

**Comment by zanat** [comment]
Resolved:
just augmented 

> nwanx 

to higher value in source file :

> input_parameters.f90
